% Describe how to build the user's trial structure.
% TrialsPerSet is per Block (ExperimentParams)
BaseStructParams = struct(  'SetSizes',           [1,3,5,7,9,11],   ...
                            'TrialsPerSet',       8,         ...
                            'NumDistractorTypes', 1,         ...
                            'MaxSetSizesInRow',   3,         ...
                            'MaxAbsOrPresInRow',  3);

% Describe the esthetics of each visual type.       
VisualTypesLegible = {...
... % Name          Color     Size  Direct. Freq  Phase  Ampl
    {'target',      'black',    .5, 'none', 0.8,    0,  0.5}, ...
    {'dist1',       'white', 	.5, 'none', 0.8, 	0,	0.5}, ...
    {'dist2',       'black',    .5, 'none', 0.8,    0,  0.5}, ...
    {'distPrac1',   'white',	.5, 'none', 0.8,    0,	0.5}, ...
    {'distPrac2',   'black',	.5, 'none', 0.8,	0,	0.5}};
% Size (of the dots) is in degrees of visual angle, and denotes radius.
% Phase should be in range 0-1.
% Amplitude (of the motion) is in degrees of visual angle.


% Describe how the experiment should run.
ExperimentParams = struct( 'NumBlocks',         2,  ...
                           'MaxTimePerTrial',   3,  ...
                           'MinTimePerWait',    2,  ...
                           'DotRadiusToCenter', 8,  ...
                           'BackgroundColor',   [.5,.5,.5]);