function [ep, cp, cv] = params()

% return experiment parameters (ep)

% returns search type parameters 
% feature search parameters (fp), conjunction search parameters (cp)

% returns visual parameters
% feature search visual parameters (fv), 
% conjunction search visual parameters (cv)

global luminance_LUT
global color_LUT
global luminance_bg
global color_bg

%%%%%%%%%%%%% Definition of Parameters %%%%%%%%%%%%%
% load the colours
% load(strcat('C:\Users\ANDLab\Documents\Experiments\MonitorCalibration\lookuptables', ...
%     filesep, '50cdm2-MBaxes5001_binary_Brown_eizokm20180923.mat'), ...
%     'RGB_bg', 'RGB_LM', 'RGB_lum')

load(strcat('C:\Users\ANDLab\Documents\Experiments\MonitorCalibration\lookuptables', ...
    filesep, 'MBaxes5001_binary_AND_eizokm_20240827.mat'), ...
    'RGB_bg', 'RGB_LM', 'RGB_lum')



luminance_LUT = RGB_lum;
color_LUT = RGB_LM; 
luminance_bg = RGB_bg(1,:);
color_bg = RGB_lum(1,:);


%% Experiment Parameters
% Describe how to build the user's trial structure.

scrn_res = Screen('Resolution', max(Screen('Screens')));

% Describe how the experiment should run.
% Time is in seconds.
% Radius (dot distance to center) is in degrees of visual angle.

ExperimentParams = struct(  'SetSizes', [1,2,3], ...
                            'MaxSetSizesInRow',   3, ...
                            'MaxAbsOrPresInRow',  3, ...
                            'DotRadiusToCenter', 8,  ...
                            'BackgroundColor',   [.5,.5,.5], ...
                            'W_WIDTH', scrn_res.width, ...
                            'W_HEIGHT', scrn_res.height);
                            
%% Conjunction parameters

% To implement TrialsPerSet = 8; NumBlocks = 4
% For testing/troubleshooting TrialsPerSet = 2; NumBlocks = 1
ConjunctionStructParams.luminance = struct('TrialsPerSet',       2,         ...
                                    'NumDistractorTypes', 2,         ...
                                    'BackgroundColor',   luminance_bg, ...
                                    'NumBlocks',         1,  ...
                                    'MaxTimePerTrial',   3,  ...
                                    'MinTimePerWait',    1.5);
                                
ConjunctionStructParams.color = struct('TrialsPerSet',       2,         ...
                                    'NumDistractorTypes', 2,         ...
                                    'BackgroundColor',   color_bg, ...
                                    'NumBlocks',         1,  ...
                                    'MaxTimePerTrial',   3,  ...
                                    'MinTimePerWait',    1.5);

ConjunctionStructParams.shape = struct('TrialsPerSet',       2,         ...
                                    'NumDistractorTypes', 2,         ...
                                    'BackgroundColor',   color_bg, ...
                                    'NumBlocks',         1,  ...
                                    'MaxTimePerTrial',   3,  ...
                                    'MinTimePerWait',    1.5);

%% Visual feature types 
% Describe the esthetics of each visual type.       
% Size (of the dots) is in degrees of visual angle, and denotes radius.
% Phase should be in range 0-1.
% Amplitude (of the motion) is in degrees of visual angle.


% Luminance Conjunction search visuals
% Describe the esthetics of each visual type.       
LuminanceConjunctionVisualTypesLegible = {...
... % Name          Color     Size  Direct.    Freq    Phase   Ampl     Shape
    {'target',      'black',    1, 'vert',     0.8,     0,      1     'circle'}, ...
    {'dist1',       'white',    1, 'vert',     0.8, 	0,	    1     'circle'}, ...
    {'dist2',       'black',    1, 'horz',     0.8,     0,      1     'circle'}, ...
    {'distPrac1',   'white',	1, 'vert',     0.8,     0,	    1     'circle'}, ...
    {'distPrac2',   'black',    1, 'horz',     0.8,	    0,	    1     'circle'}};


% Color Conjunction search visuals
% Describe the esthetics of each visual type.       
ColorConjunctionVisualTypesLegible = {...
... % Name          Color     Size  Direct.     Freq    Phase   Ampl     Shape
    {'target',      'red',      .5, 'vert',     0.8,    0,      1     'circle'}, ...
    {'dist1',       'green',    .5, 'vert',     0.8, 	0,	    1     'circle'}, ...
    {'dist2',       'red',      .5, 'horz',     0.8,    0,      1     'circle'}, ...
    {'distPrac1',   'green',	.5, 'vert',     0.8,    0,	    1     'circle'}, ...
    {'distPrac2',   'red',      .5, 'horz',     0.8,	0,	    1     'circle'}};

% Shape Conjunction search visuals
% Describe the esthetics of each visual type.  
ShapeConjunctionVisualTypesLegible = {...
... % Name          Color     Size  Direct.     Freq    Phase   Ampl     Shape
    {'target',      'red',      1, 'none',      0.8,    0,      1     'circle'}, ...
    {'dist1',       'green',    1, 'none',      0.8, 	0,	    1     'circle'}, ...
    {'dist2',       'red',      1, 'none',      0.8,    0,      1     'square'}, ...
    {'distPrac1',   'green',	1, 'none',      0.8,    0,	    1     'circle'}, ...
    {'distPrac2',   'red',      1, 'none',      0.8,    0,	    1     'square'}};

ConjunctionVisualTypesLegible.luminance = LuminanceConjunctionVisualTypesLegible;
ConjunctionVisualTypesLegible.color = ColorConjunctionVisualTypesLegible;
ConjunctionVisualTypesLegible.shape = ShapeConjunctionVisualTypesLegible;

%% assign output variables 
ep = ExperimentParams;
cp = ConjunctionStructParams;
cv = ConjunctionVisualTypesLegible;

end